
version: "3.8"
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    hostname: rabbitmq
    ports:
      - 5672:5672
    networks:
      - tp_network
    
  
  client1:
    container_name: client1
    image: client:latest
    environment:
      - CLI_ID=1
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./client/config.ini:/config.ini
      - ./data/credits.csv:/credits.csv
      - ./data/ratings.csv:/ratings.csv
      - ./data/movies_metadata.csv:/movies_metadata.csv
    
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - NUM_CLIENTS=1
    networks:
      - tp_network
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./server/config.ini:/config.ini
    
  
  filter:
    container_name: filter
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./filter/config.ini:/config.ini
      - ./filter/filters/filter_2000_movies.ini:/filter_2000_movies.ini
      - ./filter/filters/filter_Arg_Spa_movies.ini:/filter_Arg_Spa_movies.ini
      - ./filter/filters/filter_Arg_movies.ini:/filter_Arg_movies.ini
      - ./filter/filters/filter_single_country_movies.ini:/filter_single_country_movies.ini
    
  transformer:
    container_name: transformer
    image: transformer:latest
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./transformer/config.ini:/config.ini

  
  aggregator:
    container_name: aggregator
    image: aggregator:latest
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./aggregator/config.ini:/config.ini
      - ./aggregator/aggregators/aggr_sent_revenue.ini:/aggr_sent_revenue.ini
    
networks:
  tp_network:
    ipam:
      driver: default
      config:
        - subnet:  172.25.125.0/24
    
