
version: "3.8"
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - tp_network
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    
  
  client1:
    container_name: client1
    image: client:latest
    environment:
      - CLI_ID=1
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./client/config.ini:/config.ini
      - ./data/credits.csv:/credits_filtered.csv
      - ./data/ratings_filtered.csv:/ratings_filtered.csv
      - ./data/movies_metadata.csv:/movies_metadata_filtered.csv
    
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - NUM_CLIENTS=1
    networks:
      - tp_network
    depends_on:
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./server/config.ini:/config.ini
    
  
  filter:
    container_name: filter
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./filter/config.ini:/config.ini
      - ./filter/filters/filter_2000_movies.ini:/filter_2000_movies.ini
      - ./filter/filters/filter_Arg_Spa_movies.ini:/filter_Arg_Spa_movies.ini
      - ./filter/filters/filter_Arg_movies.ini:/filter_Arg_movies.ini
      - ./filter/filters/filter_single_country_movies.ini:/filter_single_country_movies.ini
      - ./filter/filters/filter_decade_movies.ini:/filter_decade_movies.ini
    
  
  transformer:
    image: transformer:latest
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./transformer/config.ini:/config.ini
    deploy:
      replicas: 3
    
  
  aggregator:
    container_name: aggregator
    image: aggregator:latest
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./aggregator/config.ini:/config.ini
      - ./aggregator/aggregators/aggr_sent_revenue.ini:/aggr_sent_revenue.ini
      - ./aggregator/aggregators/aggr_country_budget.ini:/aggr_country_budget.ini
    
  
  reducer:
    container_name: reducer
    image: reducer:latest
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./reducer/config.ini:/config.ini
      - ./reducer/reducers/average.ini:/average.ini
      - ./reducer/reducers/top5.ini:/top5.ini
      - ./reducer/reducers/top10.ini:/top10.ini
      - ./reducer/reducers/max-min.ini:/max-min.ini
    
  
  joiner-ratings-1:
    container_name: joiner-ratings-1
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-ratings.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=1 # Direct integer ID
      - JOINER_REPLICA_COUNT=2 # Direct integer count
    
  joiner-ratings-2:
    container_name: joiner-ratings-2
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-ratings.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=2 # Direct integer ID
      - JOINER_REPLICA_COUNT=2 # Direct integer count
    
  
  joiner-credits-1:
    container_name: joiner-credits-1
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-credits.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=1 # Direct integer ID
      - JOINER_REPLICA_COUNT=2 # Direct integer count
    
  joiner-credits-2:
    container_name: joiner-credits-2
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      - server
      - rabbitmq
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-credits.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=2 # Direct integer ID
      - JOINER_REPLICA_COUNT=2 # Direct integer count
    
networks:
  tp_network:
    ipam:
      driver: default
      config:
        - subnet:  172.25.125.0/24
    
