
version: "3.8"
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - tp_network
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10
    
  
  client1:
    container_name: client1
    image: client:latest
    profiles: [clients]
    environment:
      - CLI_ID=1
    networks:
      - tp_network
    depends_on:
      server:
        condition: service_started
    volumes:
      - ./client/config.ini:/config.ini
      - ./data/credits_demo.csv:/credits.csv
      - ./data/ratings_demo.csv:/ratings.csv
      - ./data/movies_metadata_demo.csv:/movies_metadata.csv
      - ./data/results_client1.json:/results.json
    
  client2:
    container_name: client2
    image: client:latest
    profiles: [clients]
    environment:
      - CLI_ID=2
    networks:
      - tp_network
    depends_on:
      server:
        condition: service_started
    volumes:
      - ./client/config.ini:/config.ini
      - ./data/credits_demo.csv:/credits.csv
      - ./data/ratings_demo.csv:/ratings.csv
      - ./data/movies_metadata_demo.csv:/movies_metadata.csv
      - ./data/results_client2.json:/results.json
    
  client3:
    container_name: client3
    image: client:latest
    profiles: [clients]
    environment:
      - CLI_ID=3
    networks:
      - tp_network
    depends_on:
      server:
        condition: service_started
    volumes:
      - ./client/config.ini:/config.ini
      - ./data/credits_demo.csv:/credits.csv
      - ./data/ratings_demo.csv:/ratings.csv
      - ./data/movies_metadata_demo.csv:/movies_metadata.csv
      - ./data/results_client3.json:/results.json
    
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - NUM_CLIENTS=3
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./server/config.ini:/config.ini
    
  
  filter-2000-movies-1:
    container_name: filter-2000-movies-1
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_2000_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=1
      - FILTER_REPLICA_COUNT=2
    
  filter-2000-movies-2:
    container_name: filter-2000-movies-2
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_2000_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=2
      - FILTER_REPLICA_COUNT=2
    
  filter-arg-spa-movies-1:
    container_name: filter-arg-spa-movies-1
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_Arg_Spa_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=1
      - FILTER_REPLICA_COUNT=1
    
  filter-arg-movies-1:
    container_name: filter-arg-movies-1
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_Arg_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=1
      - FILTER_REPLICA_COUNT=1
    
  filter-single-country-movies-1:
    container_name: filter-single-country-movies-1
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_single_country_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=1
      - FILTER_REPLICA_COUNT=1
    
  filter-decade-movies-1:
    container_name: filter-decade-movies-1
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_decade_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=1
      - FILTER_REPLICA_COUNT=1
    
  
  data-controller-movies-1:
    container_name: data-controller-movies-1
    image: data-controller:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./data_controller/data_controllers/movies.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_CONTROLLER_REPLICA_ID=1
      - DATA_CONTROLLER_REPLICA_COUNT=1
    
  data-controller-ratings-1:
    container_name: data-controller-ratings-1
    image: data-controller:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./data_controller/data_controllers/ratings.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_CONTROLLER_REPLICA_ID=1
      - DATA_CONTROLLER_REPLICA_COUNT=2
    
  data-controller-ratings-2:
    container_name: data-controller-ratings-2
    image: data-controller:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./data_controller/data_controllers/ratings.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_CONTROLLER_REPLICA_ID=2
      - DATA_CONTROLLER_REPLICA_COUNT=2
    
  data-controller-credits-1:
    container_name: data-controller-credits-1
    image: data-controller:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./data_controller/data_controllers/credits.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_CONTROLLER_REPLICA_ID=1
      - DATA_CONTROLLER_REPLICA_COUNT=2
    
  data-controller-credits-2:
    container_name: data-controller-credits-2
    image: data-controller:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./data_controller/data_controllers/credits.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_CONTROLLER_REPLICA_ID=2
      - DATA_CONTROLLER_REPLICA_COUNT=2
    
  
  transformer-1:
    container_name: transformer-1
    image: transformer:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./transformer/config.ini:/config.ini
    environment:
      - TRANSFORMER_REPLICA_ID=1
      - TRANSFORMER_REPLICAS_COUNT=2
    
  transformer-2:
    container_name: transformer-2
    image: transformer:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./transformer/config.ini:/config.ini
    environment:
      - TRANSFORMER_REPLICA_ID=2
      - TRANSFORMER_REPLICAS_COUNT=2
    
  
  aggregator-sent-1:
    container_name: aggregator-sent-1
    image: aggregator:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./aggregator/aggregators/aggr_sent_revenue.ini:/config.ini
    environment:
      - AGGR_REPLICA_ID=1
      - AGGR_REPLICA_COUNT=2
    
  aggregator-sent-2:
    container_name: aggregator-sent-2
    image: aggregator:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./aggregator/aggregators/aggr_sent_revenue.ini:/config.ini
    environment:
      - AGGR_REPLICA_ID=2
      - AGGR_REPLICA_COUNT=2
    
  aggregator-budget-1:
    container_name: aggregator-budget-1
    image: aggregator:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./aggregator/aggregators/aggr_country_budget.ini:/config.ini
    environment:
      - AGGR_REPLICA_ID=1
      - AGGR_REPLICA_COUNT=1
    
  aggregator-ratings-1:
    container_name: aggregator-ratings-1
    image: aggregator:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./aggregator/aggregators/aggr_ratings.ini:/config.ini
    environment:
      - AGGR_REPLICA_ID=1
      - AGGR_REPLICA_COUNT=1
    
  
  reducer-top5:
    container_name: reducer-top5
    image: reducer:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    environment:
      - BACKUP_FILE=backup_reducer-top5.json
      - REDUCER_NAME=reducer-top5
    volumes:
      - ./reducer/reducers/top5.ini:/config.ini
      - ./reducer/backup:/backup
    
  reducer-top10:
    container_name: reducer-top10
    image: reducer:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    environment:
      - BACKUP_FILE=backup_reducer-top10.json
      - REDUCER_NAME=reducer-top10
    volumes:
      - ./reducer/reducers/top10.ini:/config.ini
      - ./reducer/backup:/backup
    
  reducer-max-min:
    container_name: reducer-max-min
    image: reducer:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    environment:
      - BACKUP_FILE=backup_reducer-max-min.json
      - REDUCER_NAME=reducer-max-min
    volumes:
      - ./reducer/reducers/max-min.ini:/config.ini
      - ./reducer/backup:/backup
    
  reducer-average:
    container_name: reducer-average
    image: reducer:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    environment:
      - BACKUP_FILE=backup_reducer-average.json
      - REDUCER_NAME=reducer-average
    volumes:
      - ./reducer/reducers/average.ini:/config.ini
      - ./reducer/backup:/backup
    
  reducer-query1:
    container_name: reducer-query1
    image: reducer:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    environment:
      - BACKUP_FILE=backup_reducer-query1.json
      - REDUCER_NAME=reducer-query1
    volumes:
      - ./reducer/reducers/query1.ini:/config.ini
      - ./reducer/backup:/backup
    
  
  joiner-ratings-1:
    container_name: joiner-ratings-1
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-ratings.ini:/config.ini
      - ./joiner/backup:/backup
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=1
      - JOINER_REPLICA_COUNT=4
      - JOINER_NAME=joiner-ratings
      - HC_PORT=3030
      - LISTEN_BACKLOG=10
    
  joiner-ratings-2:
    container_name: joiner-ratings-2
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-ratings.ini:/config.ini
      - ./joiner/backup:/backup
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=2
      - JOINER_REPLICA_COUNT=4
      - JOINER_NAME=joiner-ratings
      - HC_PORT=3030
      - LISTEN_BACKLOG=10
    
  joiner-ratings-3:
    container_name: joiner-ratings-3
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-ratings.ini:/config.ini
      - ./joiner/backup:/backup
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=3
      - JOINER_REPLICA_COUNT=4
      - JOINER_NAME=joiner-ratings
      - HC_PORT=3030
      - LISTEN_BACKLOG=10
    
  joiner-ratings-4:
    container_name: joiner-ratings-4
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-ratings.ini:/config.ini
      - ./joiner/backup:/backup
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=4
      - JOINER_REPLICA_COUNT=4
      - JOINER_NAME=joiner-ratings
      - HC_PORT=3030
      - LISTEN_BACKLOG=10
    
  
  joiner-credits-1:
    container_name: joiner-credits-1
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-credits.ini:/config.ini
      - ./joiner/backup:/backup
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=1
      - JOINER_REPLICA_COUNT=4
      - JOINER_NAME=joiner-credits
      - HC_PORT=3030
      - LISTEN_BACKLOG=10
    
  joiner-credits-2:
    container_name: joiner-credits-2
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-credits.ini:/config.ini
      - ./joiner/backup:/backup
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=2
      - JOINER_REPLICA_COUNT=4
      - JOINER_NAME=joiner-credits
      - HC_PORT=3030
      - LISTEN_BACKLOG=10
    
  joiner-credits-3:
    container_name: joiner-credits-3
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-credits.ini:/config.ini
      - ./joiner/backup:/backup
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=3
      - JOINER_REPLICA_COUNT=4
      - JOINER_NAME=joiner-credits
      - HC_PORT=3030
      - LISTEN_BACKLOG=10
    
  joiner-credits-4:
    container_name: joiner-credits-4
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-credits.ini:/config.ini
      - ./joiner/backup:/backup
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=4
      - JOINER_REPLICA_COUNT=4
      - JOINER_NAME=joiner-credits
      - HC_PORT=3030
      - LISTEN_BACKLOG=10
    
  
  healthchecker-1:
    container_name: healthchecker-1
    image: healthcheck:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HEALTHCHECK_REPLICA_ID: 1
      HEALTHCHECK_REPLICA_COUNT: 3
      PORT: 3030
      LOGGING_LEVEL: INFO
      LISTEN_BACKLOG: 10
      NODES: >
          ["filter-arg-spa-movies-1", "filter-decade-movies-1", "data-controller-movies-1", "reducer-max-min", "transformer-1", "filter-2000-movies-2", "data-controller-credits-1", "data-controller-ratings-2", "joiner-ratings-3", "joiner-credits-2"]
    
  healthchecker-2:
    container_name: healthchecker-2
    image: healthcheck:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HEALTHCHECK_REPLICA_ID: 2
      HEALTHCHECK_REPLICA_COUNT: 3
      PORT: 3030
      LOGGING_LEVEL: INFO
      LISTEN_BACKLOG: 10
      NODES: >
          ["filter-arg-movies-1", "aggregator-budget-1", "reducer-top5", "reducer-average", "transformer-2", "aggregator-sent-1", "data-controller-credits-2", "joiner-ratings-1", "joiner-ratings-4", "joiner-credits-3"]
    
  healthchecker-3:
    container_name: healthchecker-3
    image: healthcheck:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      HEALTHCHECK_REPLICA_ID: 3
      HEALTHCHECK_REPLICA_COUNT: 3
      PORT: 3030
      LOGGING_LEVEL: INFO
      LISTEN_BACKLOG: 10
      NODES: >
          ["filter-single-country-movies-1", "aggregator-ratings-1", "reducer-top10", "reducer-query1", "filter-2000-movies-1", "aggregator-sent-2", "data-controller-ratings-1", "joiner-ratings-2", "joiner-credits-1", "joiner-credits-4"]
    
networks:
  tp_network:
    ipam:
      driver: default
      config:
        - subnet:  172.25.125.0/24
    
