
version: "3.8"
services:
  rabbitmq:
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.dockerfile
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - tp_network
    volumes:
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 10s
        timeout: 5s
        retries: 10
    
  
  client1:
    container_name: client1
    image: client:latest
    environment:
      - CLI_ID=1
    networks:
      - tp_network
    depends_on:
      server:
        condition: service_started
    volumes:
      - ./client/config.ini:/config.ini
      - ./data/credits.csv:/credits.csv
      - ./data/ratings_small.csv:/ratings.csv
      - ./data/movies_metadata.csv:/movies_metadata.csv
      - ./data/results_client1.json:/results.json
    
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - NUM_CLIENTS=1
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./server/config.ini:/config.ini
    
  
  filter_2000_movies-1:
    container_name: filter_2000_movies-1
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_2000_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=1
      - FILTER_REPLICA_COUNT=2
    
  filter_2000_movies-2:
    container_name: filter_2000_movies-2
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_2000_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=2
      - FILTER_REPLICA_COUNT=2
    
  filter_arg_spa_movies-1:
    container_name: filter_arg_spa_movies-1
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_Arg_Spa_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=1
      - FILTER_REPLICA_COUNT=1
    
  filter_arg_movies-1:
    container_name: filter_arg_movies-1
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_Arg_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=1
      - FILTER_REPLICA_COUNT=2
    
  filter_arg_movies-2:
    container_name: filter_arg_movies-2
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_Arg_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=2
      - FILTER_REPLICA_COUNT=2
    
  filter_single_country_movies-1:
    container_name: filter_single_country_movies-1
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_single_country_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=1
      - FILTER_REPLICA_COUNT=2
    
  filter_single_country_movies-2:
    container_name: filter_single_country_movies-2
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_single_country_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=2
      - FILTER_REPLICA_COUNT=2
    
  filter_decade_movies-1:
    container_name: filter_decade_movies-1
    image: filter:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./filter/filters/filter_decade_movies.ini:/config.ini
    environment:
      - FILTER_REPLICA_ID=1
      - FILTER_REPLICA_COUNT=1
    
  
  data-controller-1:
    container_name: data-controller-1
    image: data-controller:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./data_controller/config.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - DATA_CONTROLLER_REPLICA_ID=1
      - DATA_CONTROLLER_REPLICA_COUNT=1
    
  transformer:
    container_name: transformer
    image: transformer:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./transformer/config.ini:/config.ini

  
  aggregator_sent-1:
    container_name: aggregator_sent-1
    image: aggregator:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./aggregator/aggregators/aggr_sent_revenue.ini:/config.ini
    environment:
      - AGGR_REPLICA_ID=1
      - AGGR_REPLICA_COUNT=1
    
  aggregator_budget-1:
    container_name: aggregator_budget-1
    image: aggregator:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./aggregator/aggregators/aggr_country_budget.ini:/config.ini
    environment:
      - AGGR_REPLICA_ID=1
      - AGGR_REPLICA_COUNT=1
    
  
  reducer:
    container_name: reducer
    image: reducer:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./reducer/config.ini:/config.ini
      - ./reducer/reducers/average.ini:/average.ini
      - ./reducer/reducers/top5.ini:/top5.ini
      - ./reducer/reducers/top10.ini:/top10.ini
      - ./reducer/reducers/max-min.ini:/max-min.ini
    
  
  joiner-ratings-1:
    container_name: joiner-ratings-1
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-ratings.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=1 # Direct integer ID
      - JOINER_REPLICA_COUNT=1 # Direct integer count
    
  
  joiner-credits-1:
    container_name: joiner-credits-1
    image: joiner:latest
    networks:
      - tp_network
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    links:
      - rabbitmq
    volumes:
      - ./joiner/config/joiner-credits.ini:/config.ini
    environment:
      - PYTHONUNBUFFERED=1
      - JOINER_REPLICA_ID=1 # Direct integer ID
      - JOINER_REPLICA_COUNT=1 # Direct integer count
    
networks:
  tp_network:
    ipam:
      driver: default
      config:
        - subnet:  172.25.125.0/24
    
