#!/bin/bash
CLIENT_COUNT=${1:-1}
TRANSFORMER_REPLICAS=${2:-1}
JOINER_RATINGS_REPLICAS=${3:-1}
JOINER_CREDITS_REPLICAS=${4:-1}
DATA_CONTROLLER_REPLICAS=${5:-1}

python3 compose-generator.py $CLIENT_COUNT $TRANSFORMER_REPLICAS $JOINER_RATINGS_REPLICAS $JOINER_CREDITS_REPLICAS $DATA_CONTROLLER_REPLICAS