#!/bin/bash
CLIENT_COUNT=${1:-1}
TRANSFORMER_REPLICAS=${2:-1}
JOINER_RATINGS_REPLICAS=${3:-1}
JOINER_CREDITS_REPLICAS=${4:-1}
FILTER_2000_MOVIES=${5:-1}
FILTER_ARG_MOVIES=${6:-1}
FILTER_ARG_SPA_MOVIES=${7:-1}
FILTER_DECADE_MOVIES=${8:-1}
FILTER_SINGLE_COUNTRY_MOVIES=${9:-1}

python3 compose-generator.py $CLIENT_COUNT $TRANSFORMER_REPLICAS $JOINER_RATINGS_REPLICAS $JOINER_CREDITS_REPLICAS $FILTER_2000_MOVIES $FILTER_ARG_MOVIES $FILTER_ARG_SPA_MOVIES $FILTER_DECADE_MOVIES $FILTER_SINGLE_COUNTRY_MOVIES