# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: comm.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'comm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncomm.proto\x12\x04\x63omm\"0\n\tTokenStep\x12\x14\n\x0c\x63ontainer_id\x18\x01 \x01(\x05\x12\r\n\x05ready\x18\x02 \x01(\x08\"j\n\rTokenFinished\x12\r\n\x05round\x18\x01 \x01(\x05\x12\x12\n\nstarted_by\x18\x02 \x01(\x05\x12\x11\n\tclient_id\x18\x03 \x01(\x05\x12#\n\ncontainers\x18\x04 \x03(\x0b\x32\x0f.comm.TokenStepb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'comm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOKENSTEP']._serialized_start=20
  _globals['_TOKENSTEP']._serialized_end=68
  _globals['_TOKENFINISHED']._serialized_start=70
  _globals['_TOKENFINISHED']._serialized_end=176
# @@protoc_insertion_point(module_scope)
